### ISSUE TITLE
看雪这次真的恶心到人了

### ISSUE THREAD

**Issue by x7dbg** [gajiucai-r0-MrCHEN/KanXue-MrChen-melon#2]
骂肉丝的封号，帮肉丝骂人的就编辑成***

**Comment by Naville** [comment]
那毕竟中年失业安全圈土皇帝段刚先生就指着工商管理专业天才少年陈老师赚棺材本了, 断人财路如杀人父母啊。

唉 资本
唉 美国
唉 华尔街
唉 盎撒人

刚门🙏

**Comment by MrXiao7** [comment]
0
